<?php

use Illuminate\Database\Seeder;

class Apartments extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('apartments')->insert([
            ['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	],

        	['tenchungcu' => 'Hai Bà Trưng Homeside',
            'diachi' => 'Số 90, Thượng Thanh, Long Biên, Hà Nội',
            'giaban' => '1.000.000.000',
            'thongtinchung' => 'Nhà đẹp, nội thất sang trọng',
            'thongtinchitiet' => 'Thiết kế đẹp, tận dụng được không gian, tiết kiệm chi phí,... là những gì chúng ta có thể nghĩ đến ở một ngôi nhà có gác lửng.',
            'hinhdaidien' => 'hinhdaidien',
            'trangthaiban' => 1,
        	]
        ]);
    }
}
